Pass inputs as env variables

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -1,3 +1,82 @@
-#!/bin/sh
+#!/bin/bash
 set -e
-exec composer "$@"
+
+command_string="composer"
+
+if [ -n "$action_command" ]
+then
+	command_string="$command_string $action_command"
+fi
+
+case "$action_interaction" in
+	yes)
+		# Default behaviour
+	;;
+	no)
+		command_string="$command_string --no-interaction"
+	;;
+	*)
+		echo "Invalid input for action argument: interaction  (must be yes or no)"
+		exit 1
+	;;
+esac
+
+case "$action_suggest" in
+	yes)
+		# Default behaviour
+	;;
+	no)
+		command_string="$command_string --no-suggest"
+	;;
+	*)
+		echo "Invalid input for action argument: suggest (must be yes or no)"
+		exit 1
+	;;
+esac
+
+case "$action_dev" in
+	yes)
+		# Default behaviour
+	;;
+	no)
+		command_string="$command_string --no-dev"
+	;;
+	*)
+		echo "Invalid input for action argument: dev (must be yes or no)"
+		exit 1
+	;;
+esac
+
+case "$action_progress" in
+	yes)
+		# Default behaviour
+	;;
+	no)
+		command_string="$command_string --no-progress"
+	;;
+	*)
+		echo "Invalid input for action argument: progress (must be yes or no)"
+		exit 1
+	;;
+esac
+
+case "$action_quiet" in
+	yes)
+		command_string="$command_string --quiet"
+	;;
+	no)
+		# Default behaviour
+	;;
+	*)
+		echo "Invalid input for action argument: quiet (must be yes or no)"
+		exit 1
+	;;
+esac
+
+if [ -n "$action_args" ]
+then
+	command_string="$command_string $action_args"
+fi
+
+echo "Command: $command_string"
+eval "$command_string"
